// <auto-generated />
namespace AbpPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_casegroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_casegroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201804150754511_add_casegroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
