// <auto-generated />
namespace AbpPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201804172028_add_mdict : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201804172028_add_mdict));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171229443_201804172028_add_mdict"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
